14
CAJO_SET_MEMORY 2 0
CAJO_SET_MEMORY -1 1
CAJO_SET_MEMORY 0 2
CAJO_COPY_FROM_MEMORY 0
CAJO_ADD 1
CAJO_PRINT
CAJO_JUMP_IF_POSITIVE_TO 5
CAJO_JUMP_IF_NEGATIVE_TO 1
CAJO_COPY_FROM_MEMORY 1
CAJO_JUMP_IF_NEGATIVE_TO 12
CAJO_ADD 0
CAJO_OPEN t3st3.txt 0 0
CAJO_READ 0
CAJO_PRINT
CAJO_CLOSE 0